### ISSUE TITLE
Suggested named entities but zero search results

### ISSUE THREAD

**Issue by mduering** [impresso/impresso-frontend#418]
These entities are suggested for the query "el alamein" but no resources are linked to them:

"Helden von El Alamein"
https://dev.impresso-project.ch/app/#/search?f=%5B%7B%22type%22%3A%22string%22,%22q%22%3A%22Helden%20von%20El%20Alamein%22,%22precision%22%3A%22exact%22%7D%5D&g=articles&p=1&o=-relevance

"Montgomery von El Alamein"
https://dev.impresso-project.ch/app/#/search?f=%5B%7B%22type%22%3A%22string%22,%22q%22%3A%22Montgomery%20Von%20El%20Alamein%22,%22precision%22%3A%22exact%22%7D%5D&g=articles&p=1&o=-relevance

Does this occur with other entities as well?

**Comment by danieleguido** [comment]
hi @marten, I fixed the num of results (due to the multilanguage bug, now fixed).

**Comment by mduering** [comment]
could you please check again, I tried again for Poseidon (horse) and have the same problem

https://impresso-project.ch/app/#/search?f=%5B%7B%22type%22%3A%22person%22,%22q%22%3A%5B%22aida-0001-50-Poseidon_%28horse%29%22%5D,%22op%22%3A%22OR%22%7D%5D&g=articles&p=1&o=-relevance

**Comment by mduering** [comment]
Problem persists: https://dev.impresso-project.ch/app/search?sq=CgIYAgojEAIYECodYWlkYS0wMDAxLTUwLVBvc2VpZG9uXyhob3JzZSk%3D&p=1

Wait for new data?
