### ISSUE TITLE
Ghost topics and strange errors 

### ISSUE THREAD

**Issue by mduering** [impresso/impresso-frontend#742]
Could it be that Solr still suggests topics that no longer exist and appear as "undefined" when added as filters?

Could there be a problem with I&C feature "insert most recent query"?

Here is what I wanted to do: Select a topic for exploration in the I&C view to see what are top newspapers, entities etc.

This query https://impresso-project.ch/app/compare?left=CgIYAgogCAEQAhgSKgAqFnRtLWZyLWFsbC12Mi4wX3RwNTJfZnI%3D 

yields 2 "undefined" topics in the search in column A.

How I got there:
1) add topic in topic explorer
2) go to search
3) edit search to remove a previously selected (ghost?) topic
4) go to I&C, "insert most recent query"

It seems that I&C received the query I had before editing it in Search (step 3) which is unexpected.

**Comment by theorm** [comment]
@mduering it seems that the URL above contains empty topic IDs. Impresso should not be able to create URLs like this, so it is certainly a bug. However I could not reproduce it using your steps. This means that it most likely has been fixed.

At the same time I noticed that search pills do not display topics names in I&C, which is a separate problem that I just fixed in https://github.com/impresso/impresso-frontend/pull/858.

Can you please check if you can still reproduce the problem?

**Comment by mduering** [comment]
Tried the steps above again, the problem persists. We can discuss via Skype
